SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- User AMS internal (admin, operator, kepala unit, user umum) dengan password bcrypt "dev1234"
INSERT INTO users (
  id, name, email, phone, password, photo, status,
  forgot_password_code_expiry_at, email_verification_code_expiry_at,
  created_at, updated_at, deleted_at,
  nrp, pangkatId, corpsId, ojs_api_key, is_superadmin, ams_role, is_user_simpeg,
  gender, jabatan_type, unit_kerja_custom, jabatan_custom,
  pns_id, nrpnip_lama, nopeg, npwp, npwp_file, npwp_tanggal,
  kta, kta_file, ktp, ktp_file, kartu_asabri, kartu_pegawai,
  bpjs, bpjs_file, kk, kk_file, nolabel, karis, noreg,
  foto_samping, foto_depan, gelar_depan, gelar_belakang,
  lahir_tempat, lahir_tanggal, akte_kelahiran_file, akte_kelahiran,
  nohp, notelp, email_personal, email_kantor, alamat_rumah, pos_kode,
  jenis_kawin_nama, tkpendidikan_no, tkpendidikan_nama, pendidikan_nama,
  agama_nama, status_hidup, pensiun_tmt, pensiun_sk,
  akte_meninggal_file, akte_meninggal, akte_meninggal_tanggal,
  cpns_tmt, cpns_sk_no, cpns_sk_file, cpns_sk_tanggal,
  pangkat_awal_tmt, pangkat_tmt, pns_tmt, pns_sk_tanggal, pns_sk_no, pns_sk_file,
  tni_tmt, tni_sk_tanggal, tni_sk_no, perwira_tanggal, golongan3_tanggal,
  kemhan_tmt, kemhan_skep, kemhan_ket_pindah,
  jabatan_tmt, jabatan_sk_no, jabatan_sk_tanggal,
  kendaraan_dinas, mk_tahun, mk_bulan, jenis_pegawai_nama, kedudukan_hukum_nama,
  lokasi_kerja, tni_sk_file, status_biro, kartu_asabri_file,
  kpkn_nama, taspen_nama, sumberpa_nama, suku_nama,
  bup, pensiun, angkatanId,
  unitKerjaKode, jabatanKode, jabatanKepalaKode, unitOrganisasiKode, satkerKode, subSatkerKode,
  forgot_password_code, email_verification_code,
  eselonId, plain_name, unit_organisasi_custom, pegawai_id, public_id, vms_role,
  last_sync_riwayat_pangkat, last_sync_riwayat_jabatan
)
VALUES
  (
    1, 'Admin Sistem AMS', 'admin@kemhan.go.id', '081111111111',
    '$2a$12$tSQuH65ZXVKLQjsmpzzAfuJpmcmwu9Bv1N3J4agv.XhEvR2qiBt2u',
    '/images/default-profile.png', 'verified',
    NULL, NULL,
    NOW(), NOW(), NULL,
    'NRP0001', NULL, NULL, NULL, 1, 'admin', 0,
    'M', 'custom', NULL, 'Administrator Sistem',
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    'd545582f-1766-403e-98fc-bfcc0a92ff27', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL,
    NULL, 'ADMIN SISTEM AMS', NULL, 1, 'pub-admin-ams', 'admin',
    NULL, NULL
  ),
  (
    2, 'Operator BMN AMS', 'operator.bmn@kemhan.go.id', '082222222222',
    '$2a$12$tSQuH65ZXVKLQjsmpzzAfuJpmcmwu9Bv1N3J4agv.XhEvR2qiBt2u',
    '/images/default-profile.png', 'verified',
    NULL, NULL,
    NOW(), NOW(), NULL,
    'NRP0002', NULL, NULL, NULL, 0, 'user', 0,
    'M', 'custom', NULL, 'Operator BMN',
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    '0f6964a9-7bde-4a02-ba65-3a5971193bce', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL,
    NULL, 'OPERATOR BMN AMS', NULL, 2, 'pub-operator-bmn', 'user',
    NULL, NULL
  ),
  (
    3, 'Kepala Unit Pendidikan', 'kepala.unit@kemhan.go.id', '083333333333',
    '$2a$12$tSQuH65ZXVKLQjsmpzzAfuJpmcmwu9Bv1N3J4agv.XhEvR2qiBt2u',
    '/images/default-profile.png', 'verified',
    NULL, NULL,
    NOW(), NOW(), NULL,
    'NRP0003', NULL, NULL, NULL, 0, 'user', 0,
    'M', 'kepala', NULL, 'Kepala Unit Pendidikan',
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    '3dd9f687-d050-44c6-b348-1138377dcbe2', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL,
    NULL, 'KEPALA UNIT PENDIDIKAN', NULL, 3, 'pub-kepala-unit', 'user',
    NULL, NULL
  ),
  (
    4, 'Pengguna Umum AMS', 'user.umum@kemhan.go.id', '084444444444',
    '$2a$12$tSQuH65ZXVKLQjsmpzzAfuJpmcmwu9Bv1N3J4agv.XhEvR2qiBt2u',
    '/images/default-profile.png', 'verified',
    NULL, NULL,
    NOW(), NOW(), NULL,
    'NRP0004', NULL, NULL, NULL, 0, 'user', 0,
    'M', 'custom', NULL, 'Staf Administrasi',
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    '0f6964a9-7bde-4a02-ba65-3a5971193bce', NULL, NULL, NULL, NULL, NULL,
    NULL, NULL,
    NULL, 'PENGGUNA UMUM AMS', NULL, 4, 'pub-user-umum', 'user',
    NULL, NULL
  )
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  nrp = VALUES(nrp),
  email = VALUES(email),
  phone = VALUES(phone),
  password = VALUES(password),
  photo = VALUES(photo),
  status = VALUES(status),
  is_superadmin = VALUES(is_superadmin),
  ams_role = VALUES(ams_role),
  is_user_simpeg = VALUES(is_user_simpeg),
  gender = VALUES(gender),
  jabatan_type = VALUES(jabatan_type),
  jabatan_custom = VALUES(jabatan_custom),
  unitKerjaKode = VALUES(unitKerjaKode),
  pegawai_id = VALUES(pegawai_id),
  public_id = VALUES(public_id),
  vms_role = VALUES(vms_role),
  plain_name = VALUES(plain_name),
  updated_at = NOW();