name: Deploy Frontend VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Start Frontend Deployment"

            cd ~/ams-frontend

            git fetch origin
            git reset --hard origin/master

            npm install

            rm -rf .next

            npm run build

            pm2 restart ams-frontend || pm2 start npm --name ams-frontend -- start

            pm2 save

            echo "Deployment Success"